import { useState, useEffect } from "react";
import Head from "next/head";
import { PoemType } from "@/model/Types";
import { Poem } from "@/components/Poem";
import styles from "@/styles/Home.module.css";
import { BASE_URL } from "@/common/config";
import Spinner from "@/components/Spinner";

type PropTypes = {
  poems: PoemType[];
  error: string;
};

export default function Home({ poems, error }: PropTypes) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  });

  return (
    <>
      <Head>
        <title>Rhyme app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {loading && <Spinner loading={loading} />}
        {error && <h2>{error}</h2>}
        {poems?.length == 0 && <h2>No Poem found, Write one.</h2>}

        {poems?.map((poem) => (
          <Poem poem={poem} key={poem._id} />
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let poems = [];
  try {
    const res = await fetchWithTimeout(BASE_URL + "/api/poem", {}, 30000);
    poems = await res.json();
    return { props: { poems } };
  } catch (error: any) {
    console.log(error.message);
    return { props: { error: "Request timed out" } };
  }
}

function fetchWithTimeout(
  url: string,
  options: RequestInit,
  timeout: number = 5000
): Promise<Response> {
  return Promise.race([
    fetch(url, options),
    new Promise<Response>((_, reject) =>
      setTimeout(() => reject(new Error("Request timed out")), timeout)
    ),
  ]);
}
